config/routes.rb
Spree::Core::Engine.add_routes do
  # Add your extension routes here
  namespace :admin do
    resources :clouds

    resources :taxonomies do
      resources :taxons do
        collection do
          get :filter_cloud_assets
        end
      end
    end

    resources :products do
      resources :images do
        collection do
          get :filter_cloud_assets
        end
      end
    end

    resources :stores do
      collection do
        get :filter_cloud_assets
      end
    end
  end
end

app/models/spree/image/configuration/active_storage.rb
module Spree
  class Image < Asset
    module Configuration
      module ActiveStorage
        extend ActiveSupport::Concern

        included do
          if Spree.public_storage_service_name
            has_one_attached :attachment, service: Spree.public_storage_service_name
          else
            has_one_attached :attachment
          end

          validates :attachment, attached: true

          default_scope { includes(attachment_attachment: :blob) }

          def self.styles
            @styles ||= {
              mini: '48x48>',
              small: '100x100>',
              product: '240x240>',
              pdp_thumbnail: '160x200>',
              plp_and_carousel: '448x600>',
              plp_and_carousel_xs: '254x340>',
              plp_and_carousel_sm: '350x468>',
              plp_and_carousel_md: '222x297>',
              plp_and_carousel_lg: '278x371>',
              large: '600x600>',
              plp: '278x371>',
              zoomed: '650x870>'
            }
          end

          def default_style
            :product
          end
        end
      end
    end
  end
end

app/helpers/spree/admin/images_helper.rb
module Spree
  module Admin
    module ImagesHelper
      def options_text_for(image)
        if image.viewable.is_a?(Spree::Variant)
          if image.viewable.is_master?
            Spree.t(:all)
          else
            image.viewable.sku_and_options_text
          end
        else
          Spree.t(:all)
        end
      end

      def display_attachment(image)
        main_app.url_for(image.attachment)
      end

      def image?
        content_type.start_with?("image")
      end
    end
  end
end

app/views/spree/admin/images/_cloud_assets_modal_body.html.erb
<%= turbo_frame_tag "upload_asset_modal_body" do %>
  <div class="row gap-30">
    <% @cloud_assets.each do |asset| %>
        <div class="card asset-area cloud-area border-0 rounded-0">
          <div class="asset-info cloud-area">
            <%= image_tag(main_app.cdn_image_url(asset.attachment), class: 'cloud-asset-thumbnail attachment', width: '100%', height: '136px', data: { id: asset.id, name: asset.asset_file_name }) %>
          </div>
          <div class="card-body p-0">
            <%= content_tag(:p, asset.asset_file_name, class: 'cloud-asset-name p-2 rounded-bottom mb-0 card-text h-100') %>
          </div>
        </div>
    <% end %>
  </div>
<% end %>

app/views/spree/admin/images/_form.html.erb
<div class="d-flex align-items-center flex-wrap mb-3 mb-md-0">
  <div data-hook="file" class="form-group">
    <%= f.label :attachment, Spree.t(:filename), class: 'd-block' %>
    <%= f.file_field :attachment, class: 'choose-file' %>
  </div>
  <span class="or mb-0">or</span>
  <%= cloud_asset_upload_button(
      button_text: 'Upload icon',
      input_id: 'cloud_asset_image_file_name',
      hidden_field_name: 'cloud_asset_image',
      input_field_id: 'cloud_asset_image_id'
    ) %>
  </div>
  <input type="hidden" id="cloud_asset_image_id" name="cloud_asset[image]" />
</div>
<div data-hook="admin_image_form_fields" class="row">
  <div class="col-12 col-md-6">
    <div data-hook="variant" class="form-group">
      <%= f.label :viewable_id, Spree::Variant.model_name.human %>
      <%= f.select :viewable_id, @variants, {}, {class: 'select2'} %>
    </div>
  </div>
  <div data-hook="alt_text" class="col-12 col-md-6">
    <div class="form-group">
      <%= f.label :alt, Spree.t(:alt_text) %>
      <%= f.text_area :alt, rows: 1, class: 'form-control' %>
    </div>
  </div>
</div>

app/views/spree/admin/images/edit.html.erb
<%= render partial: 'spree/admin/shared/product_tabs', locals: { current: :images } %>

<%= render partial: 'spree/admin/shared/error_messages', locals: { target: @image } %>

<%= form_for [:admin, @product, @image], html: { multipart: true } do |f| %>
  <div data-hook="edit_image" class="card mb-3">
    <div class="card-header">
      <h5 class="card-title mb-0 h6">
        <%= @image.attachment_file_name %>
      </h5>
    </div>
    <div class="card-body">
      <div class="form-group">
        <div data-hook="thumbnail" class="col-12 col-lg-3 mb-2">
          <%= f.label Spree.t(:thumbnail), class: 'd-block' %>
          <%= link_to image_tag(main_app.cdn_image_url(@image.url(:small))), main_app.cdn_image_url(@image.attachment) %>
        </div>
        <div class="col-12">
          <%= render partial: 'form', locals: { f: f } %>
        </div>

      </div>
    </div>
  </div>
  <div class="form-actions" data-hook="buttons">
    <%= button Spree.t('actions.update'), 'save.svg' %>
    <span class="or"><%= Spree.t(:or) %></span>
    <%= button_link_to Spree.t('actions.cancel'), spree.admin_product_images_url(@product), id: 'cancel_link', icon: 'cancel.svg' %>
  </div>
<% end %>

<%= render partial: 'spree/admin/shared/upload_cloud_asset' %>

app/views/spree/admin/images/index.html.erb
<%= render partial: 'spree/admin/shared/product_tabs', locals: { current: :images } %>

<% content_for :page_actions do %>
  <%= yield :page_actions %>
  <%= external_page_preview_link(@product) %>
  <%= button_link_to(Spree.t(:new_image), spree.new_admin_product_image_url(@product), { class: "btn-success", icon: 'add.svg', id: 'new_image_link' }) if can? :create, Spree::Image %>
<% end %>

<% has_variants = @product.has_variants? %>

<% unless @product.variant_images.any? %>
  <div class="text-center no-objects-found m-5">
    <%= Spree.t(:no_resource_found, resource: plural_resource_name(Spree::Image)) %>.
  </div>
<% else %>
<div class="table-responsive border rounded bg-white">
  <table class="table sortable" data-hook="images_table" data-sortable-link="<%= update_positions_admin_product_images_url(@product) %>">
    <thead class="text-muted">
      <tr data-hook="images_header">
        <th></th>
        <th class="text-center">
          <%= Spree.t(:thumbnail) %>
        </th>
        <% if has_variants %>
          <th class="text-center">
            <%= Spree::Variant.model_name.human %>
          </th>
        <% end %>
        <th>
          <%= Spree.t(:alt_text) %>
        </th>
        <th class="actions"></th>
      </tr>
    </thead>

    <tbody id="sortVert">
      <% (@product.variant_images).each do |image| %>
        <tr id="<%= spree_dom_id image %>" data-hook="images_row">
          <td class="move-handle text-center">
            <% if can? :edit, image %>
              <%= svg_icon name: "grip-vertical.svg", width: '18', height: '18' %>
            <% end %>
          </td>
          <td class="image text-center">
            <div class="admin-product-image-container small-img">
              <%= link_to image_tag(main_app.cdn_image_url(image.attachment)), main_app.cdn_image_url(image.attachment), target: :blank %>
            </div>
          </td>
          <% if has_variants %>
            <td class="text-center"><%= options_text_for(image) %></td>
          <% end %>
          <td><%= image.alt %></td>
          <td class="actions">
            <span class="d-flex justify-content-end">
              <%= link_to_with_icon('edit.svg', Spree.t(:edit), spree.edit_admin_product_image_url(@product, image), class: 'btn btn-light btn-sm', no_text: true, data: { action: 'edit' }) if can? :edit, image %>
              <%= link_to_delete(image, { url: spree.admin_product_image_url(@product, image), no_text: true }) if can? :destroy, image %>
            </span>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<% end %>

app/views/spree/admin/images/new.html.erb
<%= render partial: 'spree/admin/shared/product_tabs', locals: { current: :images } %>

<%= render partial: 'spree/admin/shared/error_messages', locals: { target: @object } %>

<% content_for :page_title do %>
  <%= Spree.t(:new_image) %>
<% end %>

<%= form_for [:admin, @product, @image], html: { multipart: true } do |f| %>
  <fieldset data-hook="new_image">
    <%= render partial: 'form', locals: { f: f } %>

    <div class="form-actions" data-hook="buttons">
      <%= button Spree.t('actions.create'), 'save.svg' %>
      <span class="or"><%= Spree.t(:or) %></span>
      <%= button_link_to Spree.t('actions.cancel'), spree.admin_product_images_url(@product), icon: 'delete.svg', id: 'cancel_link' %>
    </div>
  </fieldset>
<% end %>
<%= render partial: 'spree/admin/shared/upload_cloud_asset', locals: {resource: @product, url: filter_cloud_assets_admin_product_images_path } %>