config/routes.rb
Spree::Core::Engine.add_routes do
  # Add your extension routes here
  namespace :admin do
    resources :clouds

    resources :taxonomies do
      resources :taxons do
        collection do
          get :filter_cloud_assets
        end
      end
    end

    resources :products do
      resources :images do
        collection do
          get :filter_cloud_assets
        end
      end
    end

    resources :stores do
      collection do
        get :filter_cloud_assets
      end
    end
  end
end

app/views/spree/admin/stores/edit.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:store) %>
  <%= render partial: 'spree/admin/stores/tabs', locals: {current: :details} %>
<% end %>
<%= render partial: 'spree/admin/shared/error_messages', locals: { target: @store } %>
<%= form_for [:admin, @store] do |f| %>
  <fieldset>
    <%= render partial: 'form', locals: { f: f } %>
    <div class="form-actions" data-hook="buttons">
      <%= button Spree.t('actions.update'), 'save.svg', 'submit', {class: 'btn-primary', data: { disable_with: "#{ Spree.t(:saving) }..." }} %>

      <%= link_to_with_icon 'delete.svg', Spree.t(:delete), spree.admin_store_url(@store), { class: 'btn btn-danger float-right', data: { confirm: Spree.t(:are_you_sure), method: :delete } } if can?(:delete, @store) && @store.can_be_deleted? %>
    </div>
  </fieldset>
<% end %>
<%= render partial: 'spree/admin/shared/upload_cloud_asset', locals: {resource: @store, url: filter_cloud_assets_admin_stores_path } %>

app/views/spree/admin/stores/new.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:add_store) %>
<% end %>
<%= form_for @store, url: spree.admin_stores_path(@store), data: { turbo: false } do |f| %>
  <fieldset>
    <%= render partial: 'form', locals: { f: f } %>
    <%= render partial: 'spree/admin/shared/new_resource_links', locals: { collection_url: spree.admin_stores_path(@store) } %>
  </fieldset>
<% end %>
<%= render partial: 'spree/admin/shared/upload_cloud_asset', locals: {resource: @store, url: filter_cloud_assets_admin_stores_path } %>