config/routes.rb
Spree::Core::Engine.add_routes do
  # Add your extension routes here
  namespace :admin do
    resources :clouds

    resources :taxonomies do
      resources :taxons do
        collection do
          get :filter_cloud_assets
        end
      end
    end

    resources :products do
      resources :images do
        collection do
          get :filter_cloud_assets
        end
      end
    end

    resources :stores do
      collection do
        get :filter_cloud_assets
      end
    end
  end
end

app/views/spree/admin/taxons/_assets_form.html.erb
<%= f.field_container :icon do %>
  <%= f.label :icon, Spree.t(:header_banner), class: 'mb-3' %>
  <%= image_tag(main_app.cdn_image_url(@taxon.icon.try(:attachment)), class: 'w-100') if @taxon.icon %>
  <%= f.file_field :icon, class: 'mt-3' %>
  <% if @taxon.icon.present? %>
    <%= link_to Spree.t(:remove_image), remove_icon_admin_taxonomy_taxon_url(@taxonomy.id, @taxon.id), method: :delete %>
  <% end %>
  <span class="or mb-0">or</span>
  <%= cloud_asset_upload_button(
      button_text: 'Upload icon',
      input_id: 'cloud_asset_icon_file_name',
      hidden_field_name: 'cloud_asset_icon',
      input_field_id: 'cloud_asset_icon_id'
    ) %>
  </div>
  <input type="hidden" id="cloud_asset_icon_id" name="cloud_asset[icon]" />
<% end %>

app/views/spree/admin/taxons/edit.html.erb
<%= render partial: 'spree/admin/taxons/tabs', locals: {current: :details} %>

<% content_for :page_actions do %>
  <%= external_page_preview_link(@taxon) %>
<% end %>

<%# Because otherwise the form would attempt to use to_param of @taxon %>
<% form_url = admin_taxonomy_taxon_path(@taxonomy.id, @taxon.id) %>

<%= render partial: 'spree/admin/shared/error_messages', locals: { target: @taxon } %>

<%= form_for [:admin, @taxonomy, @taxon], method: :put, url: form_url, html: { multipart: true } do |f| %>
  <%= render 'form', f: f %>

  <div class="form-actions" data-hook="buttons">
    <%= button Spree.t('actions.update'), 'save.svg' %>
    <span class="or"><%= Spree.t(:or) %></span>
    <%= button_link_to Spree.t('actions.cancel'), edit_admin_taxonomy_url(@taxonomy), icon: "cancel.svg" %>
  </div>
<% end %>
<%= render partial: 'spree/admin/shared/upload_cloud_asset', locals: {resource: @taxon, url: filter_cloud_assets_admin_taxonomy_taxons_path } %>

app/views/spree/admin/taxons/new.html.erb
<% content_for :page_title do %>
  <%= link_to Spree.t(:taxonomies), spree.admin_taxonomies_url %> /
  <%= link_to @taxonomy.root.name, spree.edit_admin_taxonomy_url(@taxonomy) %> / New
<% end %>

<%= render partial: 'spree/admin/shared/error_messages', locals: { target: @taxon } %>

<%= form_for [:admin, @taxonomy, @taxon] do |f| %>
  <%= render 'form', f: f %>
  <div class="form-actions" data-hook="buttons">
    <%= button Spree.t('actions.create'), 'save.svg' %>
    <span class="or"><%= Spree.t(:or) %></span>
    <%= button_link_to Spree.t('actions.cancel'), edit_admin_taxonomy_url(@taxonomy), icon: "cancel.svg" %>
  </div>
<% end %>
<%= render partial: 'spree/admin/shared/upload_cloud_asset', locals: {resource: @taxon, url: filter_cloud_assets_admin_taxonomy_taxons_path } %>